### ISSUE TITLE
Problem with klustaviewa

### ISSUE THREAD

**Issue by maurotoro** [kwikteam/klusta#24]
Dear All,
I'm having a problem that I don't know how to understand, 
I'm running klusta on a macbook pro with OSX 10.11.4 (15E65), I followed the instructions to install given on the quick install and tryed with the data and .prm in the documentation. Everything runs, but on the GUI I don't get access to the merge or split options, they are grayed out as seen on the screenshot.
Where did I go wrong?

Many thanks!
<img width="334" alt="screen shot 2016-06-16 at 14 54 48" src="https://cloud.githubusercontent.com/assets/7747615/16119201/53090f9c-33d2-11e6-96ad-526ca0a11b7f.png">

**Comment by nippoo** [comment]
Hi,

For a merge you have to select two or more clusters.

For a split, you have to select the spikes you want to split, by right-clicking a polygon in the FeatureView with your mouse.

For more help just press "H" in the GUI!

**Comment by maurotoro** [comment]
Many thanks for the response, as most of the time the problem was between the keyboard and the screen,

Thanks!

**Comment by nippoo** [comment]
No worries - the documentation is lacking, so not your fault!
