### ISSUE TITLE
successfully installed, but can't use it

### ISSUE THREAD

**Issue by atomquery** [kwikteam/klusta#32]
Hi guys,

I'm new to klusta and python. I successfully installed it. But when I try 'klusta hybrid_10sec.prm', it says 'klusta is not recognized as an internal or exteral command, operable program or batch file.' I already activated klusta. How can I deal with this? Many thanks. 

windows 7

E. Quin

**Comment by rossant** [comment]
Hi, could you send a screenshot of the terminal?

**Comment by atomquery** [comment]
![image](https://cloud.githubusercontent.com/assets/24408248/21346293/149156c4-c6a4-11e6-92f4-9c734a3b7a23.png)
Here is the screenshot. Thx.

**Comment by rossant** [comment]
It looks correct. Can you do `pip install klusta` after doing `activate klusta`, and then try again `klusta`.

**Comment by atomquery** [comment]
It works now!! Thanks for your solution!

**Comment by rossant** [comment]
:+1:
