### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by kingg0218** [kwikteam/klusta#33]
Hi, I had some issue with klustaviewa. So I just tried to reinstall the whole klusta.
I uninstalled miniconda and reinstall it and tried to install klusta
But I bumped into an error below.

 C:\Users\MNS>conda env create -n klusta -f environment.yml

Fetching package metadata ...........
Solving package specifications: .
mkl-2017.0.1-0 100% |###############################| Time: 0:00:27   4.86 MB/s
jpeg-8d-vc14_2 100% |###############################| Time: 0:00:00   4.10 MB/s
python-3.5.2-0 100% |###############################| Time: 0:00:08   3.77 MB/s
tk-8.5.18-vc14 100% |###############################| Time: 0:00:00   5.17 MB/s
zlib-1.2.8-vc1 100% |###############################| Time: 0:00:00   4.89 MB/s
colorama-0.3.7 100% |###############################| Time: 0:00:00   2.44 MB/s
cython-0.25.2- 100% |###############################| Time: 0:00:00   4.07 MB/s
decorator-4.0. 100% |###############################| Time: 0:00:00   2.82 MB/s
hdf5-1.8.15.1- 100% |###############################| Time: 0:00:00   4.32 MB/s
ipython_genuti 100% |###############################| Time: 0:00:00   3.52 MB/s
libpng-1.6.27- 100% |###############################| Time: 0:00:00   4.50 MB/s
libtiff-4.0.6- 100% |###############################| Time: 0:00:00   5.85 MB/s
numpy-1.11.3-p 100% |###############################| Time: 0:00:00   6.75 MB/s
path.py-10.1-p 100% |###############################| Time: 0:00:00   7.49 MB/s
pygments-2.1.3 100% |###############################| Time: 0:00:00   6.65 MB/s
pyparsing-2.1. 100% |###############################| Time: 0:00:00   7.73 MB/s
pytz-2016.10-p 100% |###############################| Time: 0:00:00   8.45 MB/s
setuptools-27. 100% |###############################| Time: 0:00:00   5.88 MB/s
simplegeneric- 100% |###############################| Time: 0:00:00   1.96 MB/s
sip-4.18-py35_ 100% |###############################| Time: 0:00:00   7.59 MB/s
six-1.10.0-py3 100% |###############################| Time: 0:00:00   2.19 MB/s
wcwidth-0.1.7- 100% |###############################| Time: 0:00:00   1.55 MB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00   5.97 MB/s
win_unicode_co 100% |###############################| Time: 0:00:00   3.51 MB/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00   1.82 MB/s
h5py-2.6.0-np1 100% |###############################| Time: 0:00:00   7.92 MB/s
pickleshare-0. 100% |###############################| Time: 0:00:00   1.96 MB/s
pip-9.0.1-py35 100% |###############################| Time: 0:00:00   6.64 MB/s
prompt_toolkit 100% |###############################| Time: 0:00:00   7.63 MB/s
python-dateuti 100% |###############################| Time: 0:00:00   8.27 MB/s
qt-4.8.7-vc14_ 100% |###############################| Time: 0:00:10   5.20 MB/s
scipy-0.18.1-n 100% |###############################| Time: 0:00:04   2.77 MB/s
traitlets-4.3. 100% |###############################| Time: 0:00:00   1.55 MB/s
ipython-5.2.2- 100% |###############################| Time: 0:00:00   3.93 MB/s
pyqt-4.11.4-py 100% |###############################| Time: 0:00:00   5.91 MB/s
matplotlib-1.5 100% |###############################| Time: 0:00:01   5.59 MB/s
ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'defaults::qt-4.8.7-vc14_9'.
UnicodeDecodeError('utf-8', b'        1\xb0\xb3 \xc6\xc4\xc0\xcf\xc0\xcc \xba\xb9\xbb\xe7\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.\r\n', 9, 10, 'invalid start byte')
Attempting to roll back.

UnicodeDecodeError('utf-8', b'        1\xb0\xb3 \xc6\xc4\xc0\xcf\xc0\xcc \xba\xb9\xbb\xe7\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.\r\n', 9, 10, 'invalid start byte')

C:\Users\MNS>

I use Window 10, 64bit.
And I installed python 3.5 miniconda for 64bit.
Do you have any idea about this error?
Thanks,

Kibong

**Comment by rossant** [comment]
Yes the installation instructions no longer work for Windows. There is an experimental all-in-one installer here: https://www.dropbox.com/s/tm8xyk5c322qgys/klustaviewa-setup.exe -- I'll update the instructions soon on the website
You have to uninstall all previous installations before.

**Comment by kingg0218** [comment]
Thank you for quick response.
Is that installer also for installation of klusta, not only klustaviewa?
And should I erase miniconda3?

**Comment by rossant** [comment]
Yes you should erase miniconda3. In principle it is for KlustaViewa only, but it *might* work for klusta as well as the dependencies are the same. But I've never tested it.

**Comment by kingg0218** [comment]
Okay
I just erase miniconda 3 and install klustaviewa using the .exe file.
I can use klustaviewa in my condition.(win10, x64)
But I cannot find klusta.
Are you also working on install file for klusta?

**Comment by rossant** [comment]
I think there should be a "klusta.exe" somewhere in `c:\program files (x86)\klustaviewa\`, try to search for it in that directory

**Comment by kingg0218** [comment]
C:\Program Files\KlustaViewa>dir

2017-02-21  오후 09:43    <DIR>          .
2017-02-21  오후 09:43    <DIR>          ..
2013-07-10  오후 06:33            82,726 favicon.ico
2017-02-21  오후 09:45         2,477,793 unins000.dat
2017-02-21  오후 09:43           803,493 unins000.exe
2017-02-21  오후 09:45    <DIR>          WinPython-64bit-2.7.6.4


I cannot find klusta.exe and I found the klustaviewa file in program files, not program files (x86)

**Comment by rossant** [comment]
should be `C:\Program Files\KlustaViewa\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\Scripts\klusta.exe`

**Comment by kingg0218** [comment]
Thanks!
I found it.

C:\Program Files\KlustaViewa\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\Scripts>klusta.exe
Usage: klusta-script.py [OPTIONS] PRM_FILE

Error: Missing argument "prm_file".

I blocked on this message when I open the klusta.exe file.
It dosen't work but I guess you guys are working on it.

Thank you again for your hard work here. It is really helpful :D
-Kibong

**Comment by rossant** [comment]
To use klusta you have to do `klusta.exe someprmfile.prm` in the directory where you have your data files and your PRM file.

**Comment by LINYANGNEU** [comment]
There is only one installer for win64bit system. Can I asked for the installer for win32bit? I had the same issue when I install Miniconda&klusta
Thanks!

**Comment by LINYANGNEU** [comment]
I installed the new klustaviewa in 64bit system and found the klusta.exe file. But it crashed when I tried to install it. I just want to know how to use klusta in the new version of klustaviewa.
THANKS!

**Comment by LINYANGNEU** [comment]
I just cannot open 'klusta.exe' file.

**Comment by rossant** [comment]
what's the full error message?

**Comment by LINYANGNEU** [comment]
no error message. I just find the exe file and double click the file. A terminal jump out and then disappear.

**Comment by rossant** [comment]
You can't just double click on the file. It doesn't work like that. You have to create a PRM file, open a terminal, and type `klusta.exe someprmfile.prm`. The documentation is [here](http://klusta.readthedocs.io/en/latest/).
