### ISSUE TITLE
Installation problem on Linux - klustakwik2 not installed

### ISSUE THREAD

**Issue by amansaleem** [kwikteam/klusta#39]
Hi,

I just installed klusta on a Linux machine following your instructions. It raised a few issues (I didn't keep track of them).

I tried running klusta on the sample data set. "hybrid_10sec". I got the following error:
ImportError: No module named 'klustakwik2'

I tried to reinstall klustakwik2 using: pip install klustakwik2. I'm attaching the error 

I get the following error message at the end: 

Failed building wheel for klustakwik2
Command "/home/amanadmin/miniconda3/envs/klusta/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t3gq66n8/klustakwik2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-f7pbfsjx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-t3gq66n8/klustakwik2/

The other messages it pops out are in the attached file:
[errormsg.txt](https://github.com/kwikteam/klusta/files/1026778/errormsg.txt)

**Comment by rossant** [comment]
Hi, can you try: `sudo apt-get install g++` ?

**Comment by amansaleem** [comment]
Great, it worked.
