### ISSUE TITLE
Installation does not work with python 3.8

### ISSUE THREAD

**Issue by TRuikes** [kwikteam/klusta#64]
When running `conda env create -f environment.yml` I got the error:

    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/conda/envs/klusta/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74lyaoqt/klustakwik2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74lyaoqt/klustakwik2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5l16j9o3/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Specifying the python version in the .yml to 3.5 fixed the problem:
   -python=3.5

**Comment by thisisbagas** [comment]
i have the same problem, running on anaconda environment. it showed "error: command 'gcc' failed with exit status 1" when installing klustakwik2 with pip

**Comment by ruxyb2004k** [comment]
Did you guys solve the problem? I have the same issue when trying to install klusta.
