### ISSUE TITLE
graphical issues

### ISSUE THREAD

**Issue by johsthomsen** [kwikteam/klusta#65]
Klusta worked fine until recently. I think the problem could be related to a windows update. The kwik-gui is messed up. I reinstalled everything, but it did not solve the problem. My Windows version is 10 Pro 1809. 
Any suggestions would be appreciated.
Regards
![kwik-gui](https://user-images.githubusercontent.com/60380587/73243322-8f6f4780-41a7-11ea-9b02-5b4f4b9351d2.png)

**Comment by rossant** [comment]
It might be a graphics driver issue. What is your graphics chipset? If you have two, for example Intel and nvidia, you should install the latest nvidia drivers and make sure that the nvidia is used and not the intel one for phy.

**Comment by johsthomsen** [comment]
Thanks for the suggestion. I have only one GPU: Intel HD Graphics 630 with all the drivers up to date.

**Comment by rossant** [comment]
closing as duplicate to https://github.com/cortex-lab/phy/issues/946, see discussion there
